#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi
#usermodmap=$HOME/.Xmodmap
userresources=$HOME/.Xresources
if [ -f $userresources ]; then  xrdb -merge $userresources;  fi
#if [ -f $usermodmap ]; then  xmodmap $usermodmap;  fi
/usr/bin/xset -b
/usr/bin/xset +fp /usr/share/fonts/local
/usr/bin/xset fp rehash
/usr/bin/setxkbmap -option "ctrl:nocaps"
# Make sure above commands before the 'exec' command.
# LANG="zh_CN.UTF-8"
exec startxfce4
# exec gnome-session
# exec startkde
# ...or the Window Manager of your choice
