hello
    {206}{251}Ooh! Careful, Ho           mer!   

     {254}{311}There's                no time. We          're late.   

{369}{424}O little t
own of Bethlehem

    {424}{455}O li	ttle town of Be	thl             ehem     

{457}{570}How s
till we 
see	 th	e el	ie     


{573}{637}-Excuse me
. Pardon me.

   {640}{685}- Sorry. Ex
   cuse me.|- Hey, Norm           an, how's i             t goin'?   
  {777}{999}
